version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: eventzone-db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    user: "0:0" # Run as root to avoid permission issues during initialization

  webapp:
    build: .
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LocalDB=Server=eventzone-db;Database=eventzone;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

volumes:
  sqlserver-data:
    driver: local
