#!/bin/bash
# Wait for SQL Server to start
sleep 30s

# Run the SQL commands to create the database
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'eventzone') CREATE DATABASE [eventzone]"
