version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: eventzone.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_LocalDB=Server=eventzone.database;Database=eventzone;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  eventzone.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventzone.database
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/eventzone-db:/var/opt/mssql/data # thư mục lưu DB
      - ./bk:/var/opt/mssql/backup      # thư  mục chứa file backup
    
  eventzone.cache:
    image: redis:latest
    container_name: eventzone.cache
    restart: always
    ports:
      - "6379:6379"
