name: Build and deploy ASP.Net Core app to VPS - EVENTZONE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push identity migration image
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: WebAPI/Dockerfile
          push: true
          tags: lequocuy/eventzone.api:latest

  deploy:
    name: Deploying to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            ls -la
            cd /home/uydev/code/eventzone
            ls -la
            docker compose pull
            docker compose up -d --build
